// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AcompananteContext))]
    partial class AcompananteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Acompanante", b =>
                {
                    b.Property<int>("AcompananteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcompananteID"));

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("AcompananteID");

                    b.ToTable("Acompañante", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Horarios", b =>
                {
                    b.Property<int>("AcompananteID")
                        .HasColumnType("int");

                    b.Property<int>("Domingo")
                        .HasColumnType("int");

                    b.Property<int>("Jueves")
                        .HasColumnType("int");

                    b.Property<int>("Lunes")
                        .HasColumnType("int");

                    b.Property<int>("Martes")
                        .HasColumnType("int");

                    b.Property<int>("Miercoles")
                        .HasColumnType("int");

                    b.Property<int>("Sabado")
                        .HasColumnType("int");

                    b.Property<int>("Viernes")
                        .HasColumnType("int");

                    b.HasKey("AcompananteID");

                    b.ToTable("Horarios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Horarios", b =>
                {
                    b.HasOne("Domain.Entities.Acompanante", "Acompanante")
                        .WithOne("Horarios")
                        .HasForeignKey("Domain.Entities.Horarios", "AcompananteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acompanante");
                });

            modelBuilder.Entity("Domain.Entities.Acompanante", b =>
                {
                    b.Navigation("Horarios")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
